# Yarn 4 configuration
nodeLinker: node-modules

# Use a local Yarn binary stored in the repository (avoids admin perms)
yarnPath: .yarn/releases/yarn-4.3.1.cjs

# Disable workspace hoisting - install deps directly in each workspace
nmHoistingLimits: workspaces
enableTransparentWorkspaces: false

# Enable immutable installs for CI safety (can disable locally if needed)
immutablePatterns: []

# Optional: ensure scripts run with Node's experimental warnings off
# installConfig:
#   hoistingLimits: workspaces
